[metadata]
format.version = "1.1"

[versions]
jackson = "2.20.1"
jackson-annotations = "2.20"
jetbrainsAnnotation = "26.0.2-1"

[libraries]
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson-annotations" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrainsAnnotation" }

[plugins]
edc-build = { id = "org.eclipse.edc.edc-build", version = "1.1.5" }
